version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3

    working_directory: ~/circle-ci-aws-s3-deploy

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user

      - run:
          name: s3 deploy
          command: ~/.local/bin/aws s3 sync --delete --acl public-read ~/circle-ci-aws-s3-deploy s3://circlecis3deploy --exclude ".git/*" --region us-east-1